import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const uiIconsDir = path.join(root, 'src/shared/assets/icons');
const publicIconsDir = path.join(root, 'public/images/icons');
const indexPath = path.join(uiIconsDir, 'index.ts');

function listSvgFiles(dir) {
  if (!fs.existsSync(dir)) return [];

  const result = [];

  function walk(currentDir) {
    for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.svg')) {
        result.push(path.relative(dir, fullPath));
      }
    }
  }

  walk(dir);
  return result.sort((a, b) => a.localeCompare(b));
}

function toCamelCase(fileName) {
  return fileName
    .replace(/\.svg$/i, '')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part, idx) => {
      const normalized = part.toLowerCase();
      return idx === 0 ? normalized : normalized.charAt(0).toUpperCase() + normalized.slice(1);
    })
    .join('');
}

const uiIcons = listSvgFiles(uiIconsDir);
const publicIcons = listSvgFiles(publicIconsDir);

const violations = [];

if (publicIcons.length > 0) {
  violations.push('UI icons are forbidden in public/images/icons. Move them to src/shared/assets/icons.');
  for (const icon of publicIcons) {
    violations.push(`- public/images/icons/${icon}`);
  }
}

const uiBaseNames = new Set(uiIcons.map((file) => path.basename(file, '.svg').toLowerCase()));
for (const icon of publicIcons) {
  const baseName = path.basename(icon, '.svg').toLowerCase();
  if (uiBaseNames.has(baseName)) {
    violations.push(`Duplicate icon name in src and public: ${baseName}.svg`);
  }
}

const expectedHeader = '// Auto-generated by scripts/sync-icons-index.mjs. Do not edit manually.\n';
const expectedExports = uiIcons
  .filter((file) => !file.includes(path.sep))
  .map((file) => `export { default as ${toCamelCase(file)} } from './${file}';`)
  .join('\n');
const expectedIndex = `${expectedHeader}${expectedExports}${expectedExports.length > 0 ? '\n' : ''}`;
const currentIndex = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, 'utf8') : '';

if (currentIndex !== expectedIndex) {
  violations.push('src/shared/assets/icons/index.ts is out of sync. Run: npm run icons:sync');
}

if (violations.length > 0) {
  console.error('Icon checks failed:');
  for (const item of violations) {
    console.error(item.startsWith('-') ? item : `- ${item}`);
  }
  process.exit(1);
}

console.log('Icon checks passed.');
