services:
  postgres:
    image: postgres:16
    container_name: fungi-postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5454:5432"
    volumes:
      - fungi_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  fungi_postgres_data: