namespace BackendFungi.Contracts.Other;

public record EditorMushroomDto(
    Guid RevisionId,
    Guid? SourceMushroomId,
    string Name,
    string? SynonymousName,
    string? LatinName,
    string Family,
    bool RedBook,
    string Eatable,
    bool HasStem,
    int? StemSizeFrom,
    int? StemSizeTo,
    string? StemType,
    string? StemColor,
    string CapType,
    string CapColor,
    string CapUndersideType,
    string Description,
    string? HeaderPhotoLink,
    List<string>? ExtraPhotoLinks,
    List<string> DoppelgangerNames,
    string Status,
    Guid CreatedByUserId,
    Guid? UpdatedByUserId,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    DateTime? SubmittedAt,
    DateTime? PublishedAt,
    DateTime? ReviewedAt,
    Guid? ReviewedByUserId,
    string? ReviewNote,
    DateTime? ArchivedAt,
    int LikesCount
);
