// Auto-generated by scripts/sync-icons-index.mjs. Do not edit manually.
export { default as appleLogo } from './apple-logo.svg';
export { default as googleLogo } from './google-logo.svg';
export { default as profileIcon } from './profile-icon.svg';
export { default as searchIcon } from './search-icon.svg';
